/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitingSetupRouteImport } from './routes/waiting-setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as PatchLogRouteImport } from './routes/patch-log'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MedicationRouteImport } from './routes/medication'
import { Route as LineConnectRouteImport } from './routes/line-connect'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as ElderProfilesRouteImport } from './routes/elder-profiles'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as CarePlansRouteImport } from './routes/care-plans'
import { Route as CallHistoryRouteImport } from './routes/call-history'
import { Route as BotSettingsRouteImport } from './routes/bot-settings'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AiFollowupRouteImport } from './routes/ai-followup'
import { Route as AiAgentsRouteImport } from './routes/ai-agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as PatientsPatientIdRouteImport } from './routes/patients.$patientId'
import { Route as ElderProfilesElderIdRouteImport } from './routes/elder-profiles.$elderId'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'

const WaitingSetupRoute = WaitingSetupRouteImport.update({
  id: '/waiting-setup',
  path: '/waiting-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const PatchLogRoute = PatchLogRouteImport.update({
  id: '/patch-log',
  path: '/patch-log',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationRoute = MedicationRouteImport.update({
  id: '/medication',
  path: '/medication',
  getParentRoute: () => rootRouteImport,
} as any)
const LineConnectRoute = LineConnectRouteImport.update({
  id: '/line-connect',
  path: '/line-connect',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const ElderProfilesRoute = ElderProfilesRouteImport.update({
  id: '/elder-profiles',
  path: '/elder-profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const CarePlansRoute = CarePlansRouteImport.update({
  id: '/care-plans',
  path: '/care-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const CallHistoryRoute = CallHistoryRouteImport.update({
  id: '/call-history',
  path: '/call-history',
  getParentRoute: () => rootRouteImport,
} as any)
const BotSettingsRoute = BotSettingsRouteImport.update({
  id: '/bot-settings',
  path: '/bot-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AiFollowupRoute = AiFollowupRouteImport.update({
  id: '/ai-followup',
  path: '/ai-followup',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentsRoute = AiAgentsRouteImport.update({
  id: '/ai-agents',
  path: '/ai-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsRoute,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => PatientsRoute,
} as any)
const ElderProfilesElderIdRoute = ElderProfilesElderIdRouteImport.update({
  id: '/$elderId',
  path: '/$elderId',
  getParentRoute: () => ElderProfilesRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-agents': typeof AiAgentsRoute
  '/ai-followup': typeof AiFollowupRoute
  '/alerts': typeof AlertsRoute
  '/appointments': typeof AppointmentsRoute
  '/billing': typeof BillingRoute
  '/bot-settings': typeof BotSettingsRoute
  '/call-history': typeof CallHistoryRoute
  '/care-plans': typeof CarePlansRoute
  '/cases': typeof CasesRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/elder-profiles': typeof ElderProfilesRouteWithChildren
  '/family': typeof FamilyRoute
  '/line-connect': typeof LineConnectRoute
  '/medication': typeof MedicationRoute
  '/onboarding': typeof OnboardingRoute
  '/patch-log': typeof PatchLogRoute
  '/patients': typeof PatientsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/waiting-setup': typeof WaitingSetupRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/elder-profiles/$elderId': typeof ElderProfilesElderIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients/': typeof PatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-agents': typeof AiAgentsRoute
  '/ai-followup': typeof AiFollowupRoute
  '/alerts': typeof AlertsRoute
  '/appointments': typeof AppointmentsRoute
  '/billing': typeof BillingRoute
  '/bot-settings': typeof BotSettingsRoute
  '/call-history': typeof CallHistoryRoute
  '/care-plans': typeof CarePlansRoute
  '/cases': typeof CasesRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/elder-profiles': typeof ElderProfilesRouteWithChildren
  '/family': typeof FamilyRoute
  '/line-connect': typeof LineConnectRoute
  '/medication': typeof MedicationRoute
  '/onboarding': typeof OnboardingRoute
  '/patch-log': typeof PatchLogRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/waiting-setup': typeof WaitingSetupRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/elder-profiles/$elderId': typeof ElderProfilesElderIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients': typeof PatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-agents': typeof AiAgentsRoute
  '/ai-followup': typeof AiFollowupRoute
  '/alerts': typeof AlertsRoute
  '/appointments': typeof AppointmentsRoute
  '/billing': typeof BillingRoute
  '/bot-settings': typeof BotSettingsRoute
  '/call-history': typeof CallHistoryRoute
  '/care-plans': typeof CarePlansRoute
  '/cases': typeof CasesRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/elder-profiles': typeof ElderProfilesRouteWithChildren
  '/family': typeof FamilyRoute
  '/line-connect': typeof LineConnectRoute
  '/medication': typeof MedicationRoute
  '/onboarding': typeof OnboardingRoute
  '/patch-log': typeof PatchLogRoute
  '/patients': typeof PatientsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/waiting-setup': typeof WaitingSetupRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/elder-profiles/$elderId': typeof ElderProfilesElderIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients/': typeof PatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-agents'
    | '/ai-followup'
    | '/alerts'
    | '/appointments'
    | '/billing'
    | '/bot-settings'
    | '/call-history'
    | '/care-plans'
    | '/cases'
    | '/checkout'
    | '/dashboard'
    | '/elder-profiles'
    | '/family'
    | '/line-connect'
    | '/medication'
    | '/onboarding'
    | '/patch-log'
    | '/patients'
    | '/pricing'
    | '/register'
    | '/reports'
    | '/settings'
    | '/waiting-setup'
    | '/admin/customers'
    | '/elder-profiles/$elderId'
    | '/patients/$patientId'
    | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-agents'
    | '/ai-followup'
    | '/alerts'
    | '/appointments'
    | '/billing'
    | '/bot-settings'
    | '/call-history'
    | '/care-plans'
    | '/cases'
    | '/checkout'
    | '/dashboard'
    | '/elder-profiles'
    | '/family'
    | '/line-connect'
    | '/medication'
    | '/onboarding'
    | '/patch-log'
    | '/pricing'
    | '/register'
    | '/reports'
    | '/settings'
    | '/waiting-setup'
    | '/admin/customers'
    | '/elder-profiles/$elderId'
    | '/patients/$patientId'
    | '/patients'
  id:
    | '__root__'
    | '/'
    | '/ai-agents'
    | '/ai-followup'
    | '/alerts'
    | '/appointments'
    | '/billing'
    | '/bot-settings'
    | '/call-history'
    | '/care-plans'
    | '/cases'
    | '/checkout'
    | '/dashboard'
    | '/elder-profiles'
    | '/family'
    | '/line-connect'
    | '/medication'
    | '/onboarding'
    | '/patch-log'
    | '/patients'
    | '/pricing'
    | '/register'
    | '/reports'
    | '/settings'
    | '/waiting-setup'
    | '/admin/customers'
    | '/elder-profiles/$elderId'
    | '/patients/$patientId'
    | '/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAgentsRoute: typeof AiAgentsRoute
  AiFollowupRoute: typeof AiFollowupRoute
  AlertsRoute: typeof AlertsRoute
  AppointmentsRoute: typeof AppointmentsRoute
  BillingRoute: typeof BillingRoute
  BotSettingsRoute: typeof BotSettingsRoute
  CallHistoryRoute: typeof CallHistoryRoute
  CarePlansRoute: typeof CarePlansRoute
  CasesRoute: typeof CasesRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRoute
  ElderProfilesRoute: typeof ElderProfilesRouteWithChildren
  FamilyRoute: typeof FamilyRoute
  LineConnectRoute: typeof LineConnectRoute
  MedicationRoute: typeof MedicationRoute
  OnboardingRoute: typeof OnboardingRoute
  PatchLogRoute: typeof PatchLogRoute
  PatientsRoute: typeof PatientsRouteWithChildren
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  WaitingSetupRoute: typeof WaitingSetupRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waiting-setup': {
      id: '/waiting-setup'
      path: '/waiting-setup'
      fullPath: '/waiting-setup'
      preLoaderRoute: typeof WaitingSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patch-log': {
      id: '/patch-log'
      path: '/patch-log'
      fullPath: '/patch-log'
      preLoaderRoute: typeof PatchLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medication': {
      id: '/medication'
      path: '/medication'
      fullPath: '/medication'
      preLoaderRoute: typeof MedicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/line-connect': {
      id: '/line-connect'
      path: '/line-connect'
      fullPath: '/line-connect'
      preLoaderRoute: typeof LineConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elder-profiles': {
      id: '/elder-profiles'
      path: '/elder-profiles'
      fullPath: '/elder-profiles'
      preLoaderRoute: typeof ElderProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-plans': {
      id: '/care-plans'
      path: '/care-plans'
      fullPath: '/care-plans'
      preLoaderRoute: typeof CarePlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-history': {
      id: '/call-history'
      path: '/call-history'
      fullPath: '/call-history'
      preLoaderRoute: typeof CallHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot-settings': {
      id: '/bot-settings'
      path: '/bot-settings'
      fullPath: '/bot-settings'
      preLoaderRoute: typeof BotSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-followup': {
      id: '/ai-followup'
      path: '/ai-followup'
      fullPath: '/ai-followup'
      preLoaderRoute: typeof AiFollowupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agents': {
      id: '/ai-agents'
      path: '/ai-agents'
      fullPath: '/ai-agents'
      preLoaderRoute: typeof AiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/elder-profiles/$elderId': {
      id: '/elder-profiles/$elderId'
      path: '/$elderId'
      fullPath: '/elder-profiles/$elderId'
      preLoaderRoute: typeof ElderProfilesElderIdRouteImport
      parentRoute: typeof ElderProfilesRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ElderProfilesRouteChildren {
  ElderProfilesElderIdRoute: typeof ElderProfilesElderIdRoute
}

const ElderProfilesRouteChildren: ElderProfilesRouteChildren = {
  ElderProfilesElderIdRoute: ElderProfilesElderIdRoute,
}

const ElderProfilesRouteWithChildren = ElderProfilesRoute._addFileChildren(
  ElderProfilesRouteChildren,
)

interface PatientsRouteChildren {
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
}

const PatientsRouteChildren: PatientsRouteChildren = {
  PatientsPatientIdRoute: PatientsPatientIdRoute,
  PatientsIndexRoute: PatientsIndexRoute,
}

const PatientsRouteWithChildren = PatientsRoute._addFileChildren(
  PatientsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAgentsRoute: AiAgentsRoute,
  AiFollowupRoute: AiFollowupRoute,
  AlertsRoute: AlertsRoute,
  AppointmentsRoute: AppointmentsRoute,
  BillingRoute: BillingRoute,
  BotSettingsRoute: BotSettingsRoute,
  CallHistoryRoute: CallHistoryRoute,
  CarePlansRoute: CarePlansRoute,
  CasesRoute: CasesRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRoute,
  ElderProfilesRoute: ElderProfilesRouteWithChildren,
  FamilyRoute: FamilyRoute,
  LineConnectRoute: LineConnectRoute,
  MedicationRoute: MedicationRoute,
  OnboardingRoute: OnboardingRoute,
  PatchLogRoute: PatchLogRoute,
  PatientsRoute: PatientsRouteWithChildren,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  WaitingSetupRoute: WaitingSetupRoute,
  AdminCustomersRoute: AdminCustomersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
